[package]
edition = "2018"
name = "rtfm_examples"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rtfm = "0.5.0"
cortex-m-semihosting = "0.3.3"
panic-semihosting = "0.5.3"
heapless = "0.5.1"

[dependencies.stm32f3]
version = "0.9.0"
features = ["stm32f303", "rt"]

