[package]
edition = "2018"
name = "rtfm"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.0"
cortex-m-rtfm = "0.5.0"
cortex-m-semihosting = "0.3.3"
panic-halt = "0.2.0"
lm3s6965 = "0.1.3"
panic-semihosting = "0.5.3"
heapless = "0.5.1"

